spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/java_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: hero
    password: 1949.cn

# Logger
logging:
  level:
    com.bbxyard.mp: debug

# MP
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1 # 默认值1
      logic-not-delete-value: 0 # 默认值0