# DataSource Config
spring:
  datasource:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:p6spy:h2:mem:test
    username: root
    password: test

# Logger Config
logging:
  level:
    com.bbxyard.mp.typehandler: debug
# MyBatis-Plus 配置该演示无
